//------------------------------------------------------------------------------
// <auto-generated>
//     Этот код создан по шаблону.
//
//     Изменения, вносимые в этот файл вручную, могут привести к непредвиденной работе приложения.
//     Изменения, вносимые в этот файл вручную, будут перезаписаны при повторном создании кода.
// </auto-generated>
//------------------------------------------------------------------------------

namespace OhtaApp
{
    using System;
    using System.Collections.Generic;
    
    public partial class Orders
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Orders()
        {
            this.Services_Orders = new HashSet<Services_Orders>();
        }
    
        public int ID { get; set; }
        public string Code { get; set; }
        public System.DateTime Creation_Date { get; set; }
        public System.TimeSpan Creation_Time { get; set; }
        public string Client_Code { get; set; }
        public int ID_Status { get; set; }
        public Nullable<System.DateTime> Closing_Date { get; set; }
        public int Rental_Time_In_Minutes { get; set; }
    
        public virtual Clients Clients { get; set; }
        public virtual Statuses Statuses { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Services_Orders> Services_Orders { get; set; }
    }
}
